### ISSUE TITLE
CKEditor 5 Alpha is out

### ISSUE THREAD

**Issue by wojtekidd** [andene/texteditors#1]
Hi Andreas!
I've bumped into your list of modern JavaScript editor frameworks and just wanted to let you know that CKEditor 5 Alpha is out. You can find out more [on our blog](https://ckeditor.com/blog/CKEditor-5-A-new-era-for-rich-text-editing/).

Have a great weekend!

**Comment by khlbrg** [comment]
@wojtekidd Great! I'll add it to the list!
Great work to move to an own custom data model!
Will check this out
